version: '3.5'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_www:/var/www
      - ${PUBLIC_DIR:-/var/togovar/public}:/var/www/public
      - app_sockets:/tmp/sockets
    ports:
      - ${NGINX_PORT:-80}:80
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - sparqlist
      - virtuoso

  sparqlist:
    build:
      context: docker/sparqlist
      dockerfile: Dockerfile
    env_file: togovar-dev.env
    volumes:
      - ./sparqlist:/app/repository
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2
    env_file: togovar-dev.env
    volumes:
      - ./docker/virtuoso/bin:/usr/local/bin
      - ${VIRTUOSO_VOLUMES_LOAD:-/var/togovar/virtuoso/load}:/load:ro
      - ${VIRTUOSO_VOLUMES_DATA:-/var/togovar/virtuoso/data}:/database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  nginx_www:
    name: togovar_nginx_www_${VERSION:-2020.07}
    driver: local
  app_bundle:
    name: togovar_app_bundle_${VERSION:-2020.07}
    driver: local
  app_log:
    name: togovar_app_log_${VERSION:-2020.07}
    driver: local
  app_node_modules:
    name: togovar_app_node_modules_${VERSION:-2020.07}
    driver: local
  app_tmp:
    name: togovar_app_tmp_${VERSION:-2020.07}
    driver: local
  app_sockets:
    name: togovar_app_sockets_${VERSION:-2020.07}
    driver: local
